version: "2"

services:
  nginx:
    image: nginx:latest
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./app:/app
      - ./eventcal.nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - eventcal
  php:
    image: php:fpm
    volumes:
      - ./app:/app
      - ./log-to-stdout.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    networks:
      - eventcal

networks:
  eventcal:
    driver: bridge
